### ISSUE TITLE
Collaborate with EasySync

### ISSUE THREAD

**Issue by stokito** [larswolter/WebDAVSyncApp#1]
Your app seems similar to the https://github.com/phpbg/easysync
Maybe you can contribute to the project?
That would be great to have a good WebDAV app working with all main WebDAV providers.

The main difference is that the EasySync is only for file syncing and doesn't have plans to show files in the app.

**Comment by larswolter** [comment]
I looked into EasySync and i think another main difference is, that EasySync is an all or nothing full sync solution. 
For me it is important to only sync a single folder (that can be chossed freely even on SDCard) and to sync only in one direction.
But i might look a bit closer if it is an option to implement this folder selection and direction limits into EasySync, instead of developing my own stuff.
Showing the files in the app is not very important to me it is more a feature during development and to verify everything is working correctly.

**Comment by stokito** [comment]
Thank you for the detailed response. Currently there is only two open source apps for WebDAV available in F-droid and PlayStore: the EasySync which is really new, and Round-Sync which is a very heavy app with a full RClone inside.
So it would be really great if we can make at least one successful app with features enough for most users. This would simplify usage of self hosted web dav servers and make simpler to create a personal cloud.
